### PR TITLE
fdcan frame DLC bits modification

### PR DESCRIPTION
**Pull request by Antoine31400**
In message_ram/enums.rs, lines 41 to 56, the function that compute DLC bits should be modified.

See page 6 of document "FDCAN peripheral on STM32 devices - Application note" :
https://www.st.com/resource/en/application_note/an5348-fdcan-peripheral-on-stm32-devices-stmicroelectronics.pdf

Current function :

    pub(crate) fn dlc(&self) -> u8 {
        match self {
            DataLength::Standard(l) => *l,
            DataLength::Fdcan(l) => match l {
                0..=8 => *l,
                9..=12 => 12,
                13..=16 => 16,
                17..=20 => 20,
                21..=24 => 24,
                25..=32 => 32,
                33..=48 => 48,
                49..=64 => 64,
                _ => panic!("DataLength > 64"),
            },
        }
    }

New function proposed :

    pub(crate) fn dlc(&self) -> u8 {
        match self {
            DataLength::Standard(l) => *l,
            DataLength::Fdcan(l) => match l {
                0..=8 => *l,
                9..=12 => 9,
                13..=16 => 10,
                17..=20 => 11,
                21..=24 => 12,
                25..=32 => 13,
                33..=48 => 14,
                49..=64 => 15,
                _ => panic!("DataLength > 64"),
            },
        }
    }

### CODE REVIEW

**Comment by richardeoin** [comment]
Thanks very much for this PR @Antoine31400 ! This change is clearly very important to support FDCAN frames > 8 bytes in length.

I will tidy the commit history a little, and then merge this.

**Comment by richardeoin** [comment]
Sorry I made a mistake and had to continue this on a new Pull Request. You can find it here https://github.com/stm32-rs/fdcan/pull/21

**Comment by richardeoin** [comment]
@Antoine31400 Your changes are now available on crates.io as version 0.1.2 🎉  https://crates.io/crates/fdcan

**Comment by Antoine31400** [comment]
Thanks @richardeoin !

**Pull request closed without merging**
